// Java binding for the angzarr router. Loads the shared router-ffi cdylib
// in-process via Panama/FFM (java.lang.foreign) — final on JDK 25, so no
// --enable-preview anywhere. Protobuf message types + the angzarr dispatch
// wiring are generated by `just java-binding-gen` (buf) into
// build/generated/proto/main/java and are never committed.

plugins {
    `java-library`
    id("com.diffplug.spotless") version "6.25.0"
}

repositories { mavenCentral() }

java {
    toolchain { languageVersion = JavaLanguageVersion.of(25) }
}

dependencies {
    // protobuf-java provides the well-known types (Any, …); proto-google-common-
    // protos provides google.rpc.Status / ErrorInfo — both excluded from codegen
    // and consumed from these runtime artifacts (the genproto analog).
    api("com.google.protobuf:protobuf-java:4.28.3")
    api("com.google.api.grpc:proto-google-common-protos:2.46.0")

    testImplementation(platform("org.junit:junit-bom:5.11.3"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("org.junit.platform:junit-platform-suite")
    testImplementation("io.cucumber:cucumber-java:7.20.1")
    testImplementation("io.cucumber:cucumber-junit-platform-engine:7.20.1")
}

// The generated protobuf + angzarr wiring tree (produced by buf before build).
sourceSets {
    main {
        java { srcDir(layout.buildDirectory.dir("generated/proto/main/java")) }
    }
}

tasks.named("compileJava") {
    // buf must have populated the generated tree first (the gen recipe runs it).
    inputs.dir(layout.buildDirectory.dir("generated/proto/main/java")).optional()
}

tasks.test {
    useJUnitPlatform()
    // FFM downcalls/upcalls into the cdylib; quiet the native-access warning.
    jvmArgs("--enable-native-access=ALL-UNNAMED")
    // The cdylib the binding dlopens: ANGZARR_ROUTER_LIB, else the shared
    // target/debug tree (built in the rust image, carried forward).
    systemProperty(
        "angzarr.router.lib",
        providers.environmentVariable("ANGZARR_ROUTER_LIB").orElse(
            layout.projectDirectory.dir("../../target/debug")
                .file("libangzarr_router_ffi.so").asFile.path,
        ).get(),
    )
    testLogging { events("passed", "failed", "skipped") }
}

spotless {
    java {
        target("src/**/*.java")
        googleJavaFormat()
    }
}
